// resources/js/Pages/School/Login.jsx
import React from "react";
import { Head, useForm } from "@inertiajs/react";
import { Building2, Eye, EyeOff } from "lucide-react";

export default function SchoolLogin() {
    const [showPassword, setShowPassword] = React.useState(false);
    const { data, setData, post, processing, errors } = useForm({
        npsn: "",
        password: "",
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        post("/school/login");
    };

    return (
        <>
            <Head title="School Login" />

            <div className="min-h-screen bg-gray-50 flex flex-col justify-center py-8 sm:py-12 px-4 sm:px-6 lg:px-8">
                <div className="sm:mx-auto sm:w-full sm:max-w-md">
                    <div className="flex justify-center">
                        <Building2 className="h-12 w-12 sm:h-16 sm:w-16 text-red-600" />
                    </div>
                    <h2 className="mt-4 sm:mt-6 text-center text-2xl sm:text-3xl font-bold tracking-tight text-gray-900">
                        Dashboard Guru
                    </h2>
                    <p className="mt-2 text-center text-sm text-gray-600">
                        Masuk menggunakan NPSN dan password Anda
                    </p>
                </div>

                <div className="mt-6 sm:mt-8 sm:mx-auto sm:w-full sm:max-w-md">
                    <div className="bg-white py-6 sm:py-8 px-4 shadow sm:rounded-lg sm:px-10">
                        <form
                            className="space-y-4 sm:space-y-6"
                            onSubmit={handleSubmit}
                        >
                            <div>
                                <label
                                    htmlFor="npsn"
                                    className="block text-sm font-medium text-gray-700"
                                >
                                    NPSN Sekolah
                                </label>
                                <div className="mt-1">
                                    <input
                                        id="npsn"
                                        name="npsn"
                                        type="text"
                                        required
                                        value={data.npsn}
                                        onChange={(e) =>
                                            setData("npsn", e.target.value)
                                        }
                                        className="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-red-500 focus:border-red-500 text-sm"
                                        placeholder="Masukkan NPSN sekolah"
                                    />
                                </div>
                                {errors.npsn && (
                                    <p className="mt-2 text-sm text-red-600">
                                        {errors.npsn}
                                    </p>
                                )}
                            </div>

                            <div>
                                <label
                                    htmlFor="password"
                                    className="block text-sm font-medium text-gray-700"
                                >
                                    Password
                                </label>
                                <div className="mt-1 relative">
                                    <input
                                        id="password"
                                        name="password"
                                        type={
                                            showPassword ? "text" : "password"
                                        }
                                        required
                                        value={data.password}
                                        onChange={(e) =>
                                            setData("password", e.target.value)
                                        }
                                        className="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-red-500 focus:border-red-500 text-sm pr-10"
                                        placeholder="Masukkan password"
                                    />
                                    <button
                                        type="button"
                                        className="absolute inset-y-0 right-0 pr-3 flex items-center"
                                        onClick={() =>
                                            setShowPassword(!showPassword)
                                        }
                                    >
                                        {showPassword ? (
                                            <EyeOff className="h-4 w-4 sm:h-5 sm:w-5 text-gray-400" />
                                        ) : (
                                            <Eye className="h-4 w-4 sm:h-5 sm:w-5 text-gray-400" />
                                        )}
                                    </button>
                                </div>
                                {errors.password && (
                                    <p className="mt-2 text-sm text-red-600">
                                        {errors.password}
                                    </p>
                                )}
                            </div>

                            <div>
                                <button
                                    type="submit"
                                    disabled={processing}
                                    className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 disabled:opacity-50"
                                >
                                    {processing
                                        ? "Memproses..."
                                        : "Masuk ke Dashboard Guru"}
                                </button>
                            </div>
                        </form>

                        <div className="mt-6">
                            <div className="text-center">
                                <a
                                    href="/"
                                    className="text-sm text-gray-600 hover:text-gray-500"
                                >
                                    ← Kembali ke Halaman Utama
                                </a>
                            </div>
                        </div>

                        <div className="mt-6">
                            <div className="relative">
                                <div className="absolute inset-0 flex items-center">
                                    <div className="w-full border-t border-gray-300" />
                                </div>
                                <div className="relative flex justify-center text-sm">
                                    <span className="px-2 bg-white text-gray-500">
                                        © 2025 Arah Potensi. All rights
                                        reserved.
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}

// resources/js/Pages/SuperAdmin/Login.vue
<template>
    <div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
        <div class="max-w-md w-full space-y-8">
            <div>
                <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
                    SuperAdmin Login
                </h2>
                <p class="mt-2 text-center text-sm text-gray-600">
                    {{ title }}
                </p>
            </div>
            <form class="mt-8 space-y-6" @submit.prevent="submit">
                <div class="rounded-md shadow-sm -space-y-px">
                    <div>
                        <label for="username" class="sr-only">Username</label>
                        <input id="username" name="username" type="text" required 
                               class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" 
                               placeholder="Username" v-model="form.username">
                    </div>
                    <div>
                        <label for="password" class="sr-only">Password</label>
                        <input id="password" name="password" type="password" required 
                               class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" 
                               placeholder="Password" v-model="form.password">
                    </div>
                </div>

                <div>
                    <button type="submit" 
                            class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        Sign in
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>

<script>
export default {
    props: {
        title: String,
        version: String,
    },
    data() {
        return {
            form: {
                username: '',
                password: '',
            }
        }
    },
    methods: {
        submit() {
            this.$inertia.post('/super-admin/login', this.form)
        }
    }
}
</script>
